import { useNavigate } from "react-router-dom";

export default function TermsOfService() {
  const navigate = useNavigate();

  const sections = [
    {
      t: "1. Eligibility and Accounts",
      p: "You must be at least 18 years old (or the age of majority in your jurisdiction) to use Synterica. By using the Services, you represent and warrant that you meet this requirement. Accounts created by minors will be terminated upon discovery. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.",
    },
    {
      t: "2. Description of Services",
      p: "Synterica provides AI-driven speech analysis, feedback on fillers, pace, tone, body language, charisma, confidence markers, and progress tracking. Features may include recording uploads, real-time coaching, personalized drills, and performance analytics. We reserve the right to modify, suspend, or discontinue any aspect of the Services at any time.",
    },
    {
      t: "3. User Content",
      p: "You retain ownership of the recordings and content you upload (\"User Content\"). By uploading content, you grant Synterica a worldwide, non-exclusive, royalty-free license to use, analyze, store, and process your User Content solely to provide and improve the Services. You represent that your content does not infringe third-party rights and complies with all applicable laws.",
    },
    {
      t: "4. Acceptable Use",
      p: "You agree not to: use the Services for any illegal or unauthorized purpose; upload harmful code, viruses, or malicious content; attempt to reverse engineer, hack, or interfere with the Services; share or distribute recordings without proper consent; or use the Services to impersonate others or misrepresent your identity. Violation of these rules may result in immediate termination of your account.",
    },
    {
      t: "5. Intellectual Property",
      p: "All Synterica technology, algorithms, interfaces, and content (excluding your User Content) are owned by Synterica or its licensors. You may not copy, modify, or create derivative works without explicit permission.",
    },
    {
      t: "6. Payments and Subscriptions",
      p: "Certain features require a paid subscription. Prices are subject to change. All payments are non-refundable except as required by law. You authorize us to charge your payment method on a recurring basis. You may cancel at any time, but no refunds will be issued for partial periods.",
    },
    {
      t: "7. Termination",
      p: "We may terminate or suspend your account at our discretion for violation of these Terms. Upon termination, your right to use the Services ends, but certain sections (such as liability limitations) survive.",
    },
    {
      t: "8. Disclaimers and Limitation of Liability",
      p: "The Services are provided \"AS IS\" without warranties of any kind. Synterica does not guarantee specific improvements in speaking ability or business outcomes. To the maximum extent permitted by law, Synterica shall not be liable for any indirect, incidental, special, consequential, or punitive damages. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.",
    },
    {
      t: "9. Indemnification",
      p: "You agree to indemnify and hold Synterica harmless from any claims, damages, or expenses arising from your use of the Services or violation of these Terms.",
    },
    {
      t: "10. Governing Law",
      p: "These Terms are governed by the laws of the State of Florida, United States, without regard to conflict of laws principles. Any disputes shall be resolved exclusively in the courts located in Miami, Florida.",
    },
    {
      t: "11. Recording Consent",
      p: "You are solely responsible for obtaining any consent required by applicable law before recording, uploading, or analyzing the voice or likeness of any other person. Many jurisdictions require all-party consent for audio recordings. You agree to comply with all such laws and to indemnify Synterica against any claims arising from your failure to do so.",
    },
    {
      t: "12. AI-Generated Feedback Disclaimer",
      p: "Feedback, scores, and suggestions generated by Synterica are produced by automated AI systems and are intended for educational and self-improvement purposes only. They do not constitute professional coaching, medical, psychological, legal, or career advice. You should not rely on the Services for any high-stakes decision without independent verification.",
    },
    {
      t: "13. Third-Party Services",
      p: "The Services may rely on third-party providers (including cloud hosting, AI model providers, and analytics). We are not responsible for the availability, accuracy, or practices of those third parties, and your use of features that depend on them is subject to their respective terms.",
    },
    {
      t: "14. Beta Features",
      p: "Some features may be offered as beta, preview, or experimental. They are provided as-is, may change or be removed without notice, and may contain bugs or inaccuracies. Use of beta features is at your own risk.",
    },
    {
      t: "15. Changes to Terms",
      p: "We may update these Terms periodically. Continued use after changes constitutes acceptance of the new Terms.",
    },
    {
      t: "16. Contact",
      p: "For questions about these Terms, contact us at legal@synterica.com.",
    },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground" style={{ fontFamily: "Inter, sans-serif", padding: "0 20px 60px" }}>
      <div style={{ maxWidth: 640, margin: "0 auto" }}>
        <button onClick={() => navigate(-1)} className="text-muted-foreground" style={{ background: "none", border: "none", fontSize: 13, cursor: "pointer", padding: "20px 0" }}>← Back</button>
        <h1 className="text-foreground" style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Terms of Service</h1>
        <p className="text-muted-foreground" style={{ fontSize: 11, marginBottom: 24 }}>Last Updated: May 26, 2026</p>

        <p className="text-muted-foreground" style={{ fontSize: 13, lineHeight: 1.7, marginBottom: 32 }}>
          Welcome to Synterica ("Synterica," "we," "us," or "our"), an AI-powered platform designed to help users improve their public speaking, communication skills, charisma, and overall delivery through recording analysis, feedback, and progress tracking. By accessing or using our website, mobile applications, or services (collectively, the "Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, please do not use the Services.
        </p>

        {sections.map((s, i) => (
          <div key={i} style={{ marginBottom: 24 }}>
            <h2 style={{ fontSize: 14, fontWeight: 600, marginBottom: 6 }}>{s.t}</h2>
            <p className="text-muted-foreground" style={{ fontSize: 13, lineHeight: 1.7 }}>{s.p}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
